#!/bin/bash
#BSUB -J "TrialExample[1-80]"
#BSUB -W 1:00
#BSUB -o /rsrch4/scratch/biostatistics/xchi/comb2/%J_%I.out
#BSUB -e /rsrch4/scratch/biostatistics/xchi/comb2/%J_%I.err
#BSUB -cwd /rsrch4/home/biostatistics/xchi/comb2/trial_example/
#BSUB -q short 
#BSUB -n 1
#BSUB -M 5
#BSUB -R rusage[mem=5]
# #BSUB -N
# #BSUB -u xchi@mdanderson.org


module load miniforge3
source activate xchi
module load R/4.3.1


echo "LSB_JOBID: " $LSB_JOBID
echo "LSB_BATCH_JID: " $LSB_BATCH_JID
echo "LSB_JOBINDEX: " $LSB_JOBINDEX



cp do_calibration.R do_calibration_tmp${LSB_JOBINDEX}.R

find . -name "do_calibration_tmp${LSB_JOBINDEX}.R" -print0 | xargs -0 perl -pi -e "s/idx00/${LSB_JOBINDEX}/g"

Rscript do_calibration_tmp${LSB_JOBINDEX}.R

rm do_calibration_tmp${LSB_JOBINDEX}.R



