#!/bin/bash
#BSUB -J "s_rate[1-40]"
#BSUB -W 3:00
#BSUB -o /rsrch4/scratch/biostatistics/xchi/backfilling/%J_%I.out
#BSUB -e /rsrch4/scratch/biostatistics/xchi/backfilling/%J_%I.err
#BSUB -cwd /rsrch4/home/biostatistics/xchi/intern_backfilling/sensitivity/rate/
#BSUB -q short 
#BSUB -n 2 
#BSUB -M 10
#BSUB -R rusage[mem=10]
# #BSUB -N
# #BSUB -u xchi@mdanderson.org


module load miniforge3
source activate xchi
module load R/4.3.1


echo "LSB_JOBID: " $LSB_JOBID
echo "LSB_BATCH_JID: " $LSB_BATCH_JID
echo "LSB_JOBINDEX: " $LSB_JOBINDEX



cp main_rate.R main_tmp${LSB_JOBINDEX}.R
perl -pi -e "s/sc00/${LSB_JOBINDEX}/g" main_tmp${LSB_JOBINDEX}.R
Rscript main_tmp${LSB_JOBINDEX}.R

rm main_tmp${LSB_JOBINDEX}.R
